baseURL = "/"
languageCode = "es-es"
title = "DAR3D - Mundos Abiertos a Posibilidades"

[[menu.main]]
  name = "Criaturas"
  url = "/criaturas/"
  weight = 10

# ignoreFiles = []
staticDir = ["static"]


[params]
glb_cid = "bafybeia72hosqwsvmoj3knqp3ihe5dmuiwbayhyrvalsd3gv4ktmoit7oa"   # CID global per a tots els models
ipfsBase = "https://w3s.link/ipfs/"






